### ISSUE TITLE
Question: Does minet fetch de-duplicate the urls ?

### ISSUE THREAD

**Issue by mdamien** [medialab/minet#162]
Does minet fetch, fetch two times the same url if it's present two times in the csv ?

**Comment by Yomguithereal** [comment]
Hello @mdamien, no it does not, for at least two reasons:

1. minet must be able to process files that cannot fit in RAM. As such `minet fetch` only consumes `O(t)` memory, `t` being the number of used threads. To deduplicate urls I must be able to fit all urls into memory and I don't want to do this.
2. To be able to resume minet needs to ensure there are as much lines in the report as in the input file. If I deduplicate urls, this assertion cannot stand anymore. This said I could duplicate the report lines.

I was thinking of a flag that could take advantage of loading the whole input file into memory if this is possible or relying on some kind of lru cache but I am not really sure it would yield any advantage. My current stance on the issue is that you should deduplicate urls on your own before feeding them to minet. You can for instance use `xsv sort -u` to do so from my version of xsv [here](https://github.com/Yomguithereal/xsv/tree/prod#how-to-install) or use any tool able to perform this task.

**Comment by mdamien** [comment]
Thanks, gonna filter it myself then

A solution in minet could be that the filenames generated depends on the
url and then you can just check if the file exists but that’s armchair
design ^^

Le mar. 24 nov. 2020 à 10:00, Guillaume Plique <notifications@github.com> a
écrit :
