### ISSUE TITLE
error in installing pip install mineit

### ISSUE THREAD

**Issue by moonisali** [medialab/minet#267]
while installing mineit via pip it does not work. says,
""
Collecting mineit
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/mineit/

""

is this issue already solved?

**Comment by Yomguithereal** [comment]
Hello @moonisali. I think you made a typo. It should be minet not mineit :)

**Comment by moonisali** [comment]
oh sorry, I meant

I corrected the name but now get this error:

"  Could not find a version that satisfies the requirement minet (from versions: )
No matching distribution found for minet"

**Comment by Yomguithereal** [comment]
That is weird indeed. I just tried to install it from a py 3.7.3 environment and it worked as expected. The package is correctly distributed from pypi for py >=3.6 here: https://pypi.org/project/minet/ On what OS are you working? Are you using anaconda or something of the kind? Are you working behind a VPN or proxy or are you using custom pypi repositories?

Else here is what you can try:

1. Can you try upgrading pip `pip install -U pip` and run `pip install minet` again to see if anything was amiss?
2. Can you try wrapping the name between quotes to make sure this is not an issue with invisibles chars `pip install "minet"`?
3. Can you try using `python -m pip` instead of pip?
3. If all this fails you can still try to install directly from the github repository like this:

```
pip install git+https://github.com/medialab/minet.git
```

You can also try the [standalone](https://github.com/medialab/minet#installation) installation (if you don't require to use `minet` as a library, else this advice is moot).

**Comment by Yomguithereal** [comment]
Ok I am just reading now that you added precisions regarding `PyInstaller`. The thing is `PyInstaller` is not a dependency of minet if you install it through pip. And I see you tried to install the requirements file on your own? Are you trying to run a local version of minet to contribute somehow?

**Comment by moonisali** [comment]
Dear @Yomguithereal 
I was able to install it wihtout hassles after I found a way to correctly install pyinstall. :)
I must say one thing, your quick and humane and thoughtful replies somehow inspire me to write:
"faith in the kindness of humanity restored (again) :) 

> 
> 
> That is weird indeed. I just tried to install it from a py 3.7.3 environment and it worked as expected. The package is correctly distributed from pypi for py >=3.6 here: https://pypi.org/project/minet/ On what OS are you working? Are you using anaconda or something of the kind? Are you working behind a VPN or proxy or are you using custom pypi repositories?
> 
> Else here is what you can try:
> 
>     1. Can you try upgrading pip `pip install -U pip` and run `pip install minet` again to see if anything was amiss?
> 
>     2. Can you try wrapping the name between quotes to make sure this is not an issue with invisibles chars `pip install "minet"`?
> 
>     3. Can you try using `python -m pip` instead of pip?
> 
>     4. If all this fails you can still try to install directly from the github repository like this:
> 
> 
> ```
> pip install git+https://github.com/medialab/minet.git
> ```
> 
> You can also try the [standalone](https://github.com/medialab/minet#installation) installation (if you don't require to use `minet` as a library, else this advice is moot).

**Comment by Yomguithereal** [comment]
I am always happy to know I could help someone :). I will close this issue then. Don't hesitate to open another one if you have any other problem. If you can spare some time, I would also love to know what you intend to do with the tool.
