### ISSUE TITLE
casanova.exceptions.EmptyFileError

### ISSUE THREAD

**Issue by taniki** [medialab/minet#296]
I am trying to run minet in a github action. It fails with the following message:

```
  minet tw scrape tweets -o tweets.csv "from:@taniki #tutotal2022"
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.5/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.5/x64/lib

Collecting tweets: 0 tweets [00:00, ? tweets/s]Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/casanova/reader.py", line 151, in __init__
    fieldnames = next(self.reader)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.5/x64/bin/minet", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/minet/cli/__main__.py", line 218, in main
    fn(cli_args)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/minet/cli/twitter/__init__.py", line 33, in twitter_action
    twitter_scrape_action(cli_args)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/minet/cli/twitter/scrape.py", line 45, in twitter_scrape_action
    enricher = casanova.enricher(
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/casanova/enricher.py", line 31, in __init__
    super().__init__(input_file, no_headers=no_headers, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/casanova/reader.py", line 157, in __init__
    raise EmptyFileError
casanova.exceptions.EmptyFileError

Collecting tweets: 0 tweets [00:00, ? tweets/s]
Error: Process completed with exit code 1.
```

- [failed run](https://github.com/taniki/tutotal2022/runs/2615030542?check_suite_focus=true)
- [workflow file](https://github.com/taniki/tutotal2022/actions/runs/854900631/workflow)

**Comment by Yomguithereal** [comment]
Hello @taniki. That's weird I cannot seem to be able to reproduce locally because running `minet tw scrape tweets -o tweets.csv "from:@taniki #tutotal2022"` works fine on my end (I will check soon to see if it's related to py3.9 maybe). Can you try to put the `-o` flag after the query maybe? Like so:

```bash
minet tw scrape tweets "from:@taniki #tutotal2022" -o tweets.csv
```

Also, which version of minet are you using? By the way I vouch for you to install a specific version of the tool from your action so it does not break unexpectedly if something changes with the tool by using `pip install minet==0.52.5` for instance.

**Comment by taniki** [comment]
Yeah it works fine locally too. Gonna try what switching parameters and pinning minet version.

**Comment by taniki** [comment]
I was running what `pip install minet` provides me

**Comment by Yomguithereal** [comment]
Can you also try to set the shell to bash: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell I though it was the default but maybe it's not the case. You can also try to pass the command as a single line (without the pipe). Basically the issue is that for some reason, it's as if the command wanted to read from the stdin and failed to do so. There might be something bad with the way I test the existence of stdin piped into the program.

**Comment by Yomguithereal** [comment]
What you can try also is to create a query.csv file like so:

```csv
query
from:@taniki #tutotal2022
```

And run `minet tw scrape tweets query query.csv -o tweets.csv` as a potential workaround.

**Comment by Yomguithereal** [comment]
Or even `cat query.csv | minet tw scrape tweets query -o tweets.csv`

**Comment by taniki** [comment]
Thanks! 🙇‍♂️ it worked fine with the query as a csv.

**Comment by Yomguithereal** [comment]
Okay so this points to an error with stdin handling I guess. This won't be fun to debug though :) Also, looking at your action's log, it seems actions does not handle `\r` shenagigans correctly and I foresee the progress bar could be an issue with environments such as github actions one. Do you think some kind of `--silent` flag or `--no-progress` could be useful?

**Comment by taniki** [comment]
Tbh, I won't look at logs from a succesfull task. If it works, it works :) The task output is also collapsed in the web ui.

I did looked at a `--silent` flag then might be useful for other reasons. I also tried to use https://github.com/nektos/act to track the issue but it didn't worked out of the box and it was too much effort.

**Comment by Yomguithereal** [comment]
I am testing some things right now and as this result shows: https://github.com/medialab/minet/runs/2628644170?check_suite_focus=true something is piped by github actions into the command. This is quite strange :)

**Comment by Yomguithereal** [comment]
So I don't understand why it happens that stdin is passed as an empty stream to the command when run by GitHub actions. Nonetheless, I am wondering whether I should switch to a more explicit, and unix-traditional, way of declaring stdin passing using `-` so that I can get rid of my CLI args variadicity and stdin duck-typing.

Instead of:

```
cat file.csv | minet cmd col
```

One would need to do:

```
cat file.csv | minet cmd col -
```

And this would fix your use case and make your original command work in GitHub actions out of the box.

What do you think?

**Comment by Yomguithereal** [comment]
Ok I have found a way to detect when a dummy empty stream, such as the one GitHub actions seems to be feeding me, is fed to the commands. I have released a new version of minet (0.52.6) with the "fix". You should be able to use your original command in a GitHub action now.

**Comment by taniki** [comment]
🍾 https://github.com/taniki/tutotal2022/runs/2631733616 thanks for having looked at it :)

**Comment by Yomguithereal** [comment]
Are you somehow counting points per candidate for the next election or is this a revamp of https://www.arte.tv/fr/videos/RC-015769/tutotal/ ?

**Comment by taniki** [comment]
Both :) I am looking to get enough data to perform some amateur issue mapping
