### ISSUE TITLE
Check how YT comments format user entities

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/minet#481]

**Comment by MiguelLaura** [comment]
It seems that there is no particular format for user entities tagged in comments.
But I discovered that if we switch to HTML, we get some characters converted (' to &#039 for example), but we can access moment of the video mentioned (one example: `<a href="https://www.youtube.com/watch?v=5RJo-M5Lf7s&amp;t=0m37s">0:37</a> best moment` instead of current `0:37 best moment`)
