### ISSUE TITLE
No results on facebook posts

### ISSUE THREAD

**Issue by boogheta** [medialab/minet#674]
Even with a proper cookie, minet facebook posts on diverses groups don't return any results
Groups examples:
- https://www.facebook.com/groups/451921079480252/
- https://www.facebook.com/groups/338666043984318/
- https://www.facebook.com/groups/149518041916324/

**Comment by Yomguithereal** [comment]
The issue is the following: the scraper uses selectors that can only work by scanning the english UI. Before, we were able to force facebook to serve us pages with the english UI by editing the user's cookie. It seems this is not longer possible. Solutions can be:

1. Refactoring the selector to be language-agnostic (probably unfeasible)
2. Find a new way to force FB to serve english UI
3. Document clearly the commands by explaining how to set english UI to english

**Comment by Yomguithereal** [comment]
Adding a GET param `?locale=en_US` seem to do the trick, with the proper cookie fixed.
