### ISSUE TITLE
pain to install thoughts

### ISSUE THREAD

**Issue by paulgirard** [medialab/minet#7]
- from my experience on Linux python3.5 python3-dev seems like required by dragnet install process. Not 100% sure though.

- dragnet does not install its pip dependencies, while waiting for them to accept the PR adding those deps to minet requirements would help many users 

- finally dragnet being a large piece to get installed, it could be installed only optionally? Something like the dragnet option catch the specific dragnet module error and display the command to install it + documentation ?

**Comment by Yomguithereal** [comment]
I should investigate if it's possible to (I guess it is), to trigger a pip install programmatically from python. If so I guess triggering the install of dragnet the first time you actually require it could be a good option. Since I want to include also `pyppeteer` in the future, this could be also done likewise. This would mean more packaging issues though.

**Comment by paulgirard** [comment]
Not sure about triggering pip install automatically. Looks like a little bit invasive too me.
And this process might encounter user rights issues if not executed inside a virtualenv.

IMHO it would suffice detecting the missing dependency and print a nice documentation on how to install it.

**Comment by Yomguithereal** [comment]
> IMHO it would suffice detecting the missing dependency and print a nice documentation on how to install it.

And way easier to implement :). I'm sold!

**Comment by paulgirard** [comment]
```bash
$ debuild -us -uc ##
The program 'debuild' is currently not installed. You can install it by typing:
sudo apt install devscripts
```
an example of userfriendly fail
