### ISSUE TITLE
tiktok search-videos retrieve only 12 results at most

### ISSUE THREAD

**Issue by csamson-sf** [medialab/minet#878]
When using tiktok search-videos I used to be able to get between 300 and 400 results, now I get 12 at most, I guess Tiktok must have changed something ?
(On September 13th it was still working)

**Comment by Yomguithereal** [comment]
> I guess Tiktok must have changed something ?

That's unfortunate but possible indeed. Can you provide some command reproducing the error so I can investigate some things?

**Comment by csamson-sf** [comment]
Yes sure @Yomguithereal :
`minet tiktok search-videos -l 400 "climate change scam" > September28th_climate_change_scam_tiktok.csv`

**Comment by Yomguithereal** [comment]
@csamson-sf so it seems tiktok web search changed a little bit indeed. It is just a little bit more secure but not that much. I have pushed a commit that fixes the issue. It should be available as part of `1.0.0-a52` in some minutes.

Some notes though: the number of results returned by the web search is inconsistent across runs. Also, the search often returns the same item more than once (not only because of typical pagination hiccups). I therefore added deduplication. But I would be interested if you can use the fixed command and tell me what you observe regarding the results.

**Comment by csamson-sf** [comment]
@Yomguithereal It seems to be a bit slower but I get almost as much results as I did before so that's really great, thank you !
