### ISSUE TITLE
Fetch and cookie should obliged en https url

### ISSUE THREAD

**Issue by annelhote** [medialab/minet#99]
Not sure if it's a real issue or more a PEBCAK.
If I do :
`minet fetch -g firefox http://github.com` => Not logged
But :
`minet fetch -g firefox https://github.com` => Logged
The key is in the S of https.

**Comment by Yomguithereal** [comment]
Hello @annelhote,

For the `fetch`  command, it is expected that cookies might not be used across http/https because they are not shared by the browser, especially when those cookie are "secure". What's more the user should be able to tell whether they want to hit the http or https address so I cannot tamper with that.

For the `fb comments`, on the contrary, I believe that the tool should forgive the user for giving an http address (I believe facebook automatically redirects http to https no)?

**Comment by Yomguithereal** [comment]
Hello @annelhote. Should be fixed for `fb comments`. Will publish a release soon.
