### ISSUE TITLE
Twitter search query cannot use double quotes

### ISSUE THREAD

**Issue by Tyrannas** [medialab/minet#990]
When performing a twitter query, it's possible to search for specific expression using double quotes (and double quotes only) for instance:
"be like" OR "être comme" 

However, when using the minet twitter scrape command, query must be surrounded by double quotes and double quotes only, so it's not possible to write:
'"be like" OR "être comme"' this will raise the following error:
`minet: error: unrecognized arguments: OR être comme'`

This goes the same way with backquotes.

**Comment by lattaai8** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the Twitter scrape CLI action to properly handle queries containing double quotes. This allows users to search for specific expressions using double quotes within their queries, such as '"be like" OR "être comme"'. The change involves updating the query processing logic in the action function.

You can review changes in this commit: https://github.com/lattaai8/medialab-minet-990/commit/e1530d93dd67e15ab11b954a63934279a64f8861.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Yomguithereal** [comment]
> However, when using the minet twitter scrape command, query must be surrounded by double quotes and double quotes only, so it's not possible to write:

Why? Most shell also accepts single quotes (they often have simpler semantics than double quotes regarding interpolation). In my shell the following commands works fine:

```bash
minet tw scrape tweets '"be like" OR "être comme"'
```

Are you working in a Windows shell?

**Comment by Tyrannas** [comment]
Just tried in a git bash and it's indeed working. 
I had the problem on windows command prompt indeed ! Not sure it's an issue with minet then so I guess it can be closed

**Comment by Yomguithereal** [comment]
I tried to find how to escape double quotes in the windows command prompt and it looks like a hellscape: https://stackoverflow.com/questions/7760545/escape-double-quotes-in-parameter :)
